### ISSUE TITLE
Deploy to maven central

### ISSUE THREAD

**Issue by exabrial** [OrhanKupusoglu/sloc-maven-plugin#5]
Hello! Can you get your artifact into maven central? It's not terribly difficult, and the signup process is pretty easy: https://central.sonatype.org/publish/publish-guide

Thank you!

**Comment by OrhanKupusoglu** [comment]
Thank you for the request, much appreciated.
I am sorry for being late, currently I am quite detached from the Java world.
I am checking the link.

**Comment by exabrial** [comment]
:) no worries, your plugin is pretty cool!

**Comment by OrhanKupusoglu** [comment]
I opened [OSSRH-96993](https://issues.sonatype.org/browse/OSSRH-96993) to publish the plugin.

**Comment by OrhanKupusoglu** [comment]
I updated README.md, this time with **Google Guice**.
The reason was that without building the project the SLOC plugin run fails due to missing dependencies.
Since Google Guava is huge, I selected a slimmer project.
I am not sure about this behavior change, I think five years ago without building a project the plugin could probably run just fine.
